# Site settings
title: bren.codes
email: bren@bren.codes
description: > # this means to ignore newlines until "baseurl:"
  The website of Brenden Gifford (that's me). 
  A constant work in progress, hopefully for the better!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://brendengifford.github.io" # the base hostname & protocol for your site
twitter_username: brendengifford
github_username:  brendengifford

# Build settings
markdown: kramdown
