# A sample Gemfile
source "https://rubygems.org"

# gem "rails"
gem "bundler"
gem "coderay"
gem "colorator"
gem "ffi"
gem "formatador"
gem "guard"
gem "guard-compat"
gem "guard-jekyll-plus"
gem 'guard-livereload'
gem "jekyll"
gem "jekyll-sass-converter"
gem "jekyll-watch"
gem "kramdown"
gem "liquid"
gem "listen"
gem "lumberjack"
gem "mercenary"
gem "method_source"
gem "minitest"
gem "nenv"
gem "notiffany"
gem "power_assert"
gem "pry"
gem "rake"
gem "rb-fsevent"
gem "rb-inotify"
gem "rdoc"
gem "rouge"
gem "safe_yaml"
gem "sass"
gem "shellany"
gem "slop"
gem "test-unit"
gem "thor"
gem 'wdm', '>= 0.1.0' if Gem.win_platform?